name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "printing goodebye"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second job thing
        run: echo "this is the second job"
